apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: weather-pipeline-run-
spec:
  serviceAccountName: weather-svc
  pipelineRef:
    name: weather-pipeline
  resources:
    - name: source-repo
      resourceSpec:
        type: git
        params:
          - name: revision
            value: static
          - name: url
            value: https://github.com/ArctiqTeam/weather-app.git
    - name: weather-image
      resourceSpec:
        type: image
        params:
          - name: url
            value: gcr.io/iceberg-234522/weather:toronto
