apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: weather-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: weather-image
      type: image
  tasks:
    - name: build-weather-image
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/docker-source/
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: weather-image
    - name: deploy-weather
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: weather-image
            from:
              - build-weather-image
      params:
        - name: path
          value: /workspace/source/kubernetes/deployment.yaml #configure: may change according to your source
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
