apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/managed-by: kf
    app.kubernetes.io/name: weather
  name: weather
spec:
  ports:
  - name: http-user-port
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/managed-by: kf
    app.kubernetes.io/name: weather

