apiVersion: v1
kind: BuildConfig
metadata:
  name: arctiq-weather
  labels:
    name: arctiq-weather
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "arctiq-weather", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: CwokaXwLfG63gBP3R0jV
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      env:
      - name: GITHUB_CREDS
        value: github
      - name: APP_NAME
        value: weather
      - name: DEV_PROJECT
        value: dev
      - name: QA_REGISTRY
        value: docker://docker-registry-default.apps.<your-openshift-console>
      - name: QA_PROJECT
        value: qa
      - name: QA_TAG
        value: promoteToQA
      - name: PRODA_CLUSTER
        value: https://<your-openshift-console>     
      - name: PRODA_REGISTRY
        value: docker://docker-registry-default.apps.<your-openshift-console>
      - name: PRODA_TAG
        value: promoteToProdA
      - name: PRODA_PROJECT
        value: weather
      - name: PRODB_CLUSTER
        value: https://<your-openshift-console>    
      - name: PRODB_TAG
        value: promoteToProdB
      - name: PRODB_PROJECT
        value: weather
      - name: PRODB_REGISTRY
        value: docker://docker-registry-default.apps.<your-openshift-console>

      jenkinsfile: |-
        pipeline {
          agent {
            label 'jenkins-slave-image-mgmt'
          }
          stages {
            stage('Create Build') {
                        when {
                          expression {
                            openshift.withCluster() {
                              openshift.withProject(env.DEV_PROJECT) {
                                return !openshift.selector("bc", "weather").exists();
                              }
                            }
                          }
                        }
                        steps {
                          script {
                            openshift.withCluster() {
                              openshift.withProject(env.DEV_PROJECT) {
                                openshift.newBuild("openshift/nodejs~https://github.com/ArctiqTeam/weather-app.git", "--name=weather")
                              }
                            }
                          }
                        }
                      }
                      stage('Start Build') {
                        steps {
                          script {
                            openshift.withCluster() {
                              openshift.withProject(env.DEV_PROJECT) {
                                openshift.selector("bc", "weather").startBuild("--wait=true")
                              }
                            }
                          }
                        }
                      }
                      stage('Deploy Image in Dev') {
                        when {
                          expression {
                            openshift.withCluster() {
                              openshift.withProject(env.DEV_PROJECT) {
                                return !openshift.selector('dc', 'weather').exists()
                              }
                            }
                          }
                        }
                        steps {
                          script {
                            openshift.withCluster() {
                              openshift.withProject(env.DEV_PROJECT) {
                                def app = openshift.newApp("weather:latest", "--name=weather")
                                app.narrow("svc").expose();

                                def dc = openshift.selector("dc", "weather")
                                while (dc.object().spec.replicas != dc.object().status.availableReplicas) {
                                    sleep 10
                                }
                                openshift.set("triggers", "dc/weather", "--manual")
                              }
                            }
                          }
                        }
                      }
                      stage('Deploy DEV') {
                        steps {
                          script {
                            openshift.withCluster() {
                              openshift.withProject(env.DEV_PROJECT) {
                                openshift.selector("dc", "weather").rollout().latest();
                              }
                            }
                          }
                        }
                      }
                      stage('Tag for QA') {
                        steps {
                          script {
                            openshift.withCluster() {
                              openshift.tag("${env.DEV_PROJECT}/weather:latest", "${env.QA_PROJECT}/weather:${QA_TAG}")
                            }
                          }
                        }
                      }
                      stage('Create QA') {
                        when {
                          expression {
                            openshift.withCluster() {
                              openshift.withProject(env.QA_PROJECT) {
                                return !openshift.selector('dc', 'weather').exists()
                              }
                            }
                          }
                        }
                        steps {
                          script {
                            openshift.withCluster() {
                              openshift.withProject(env.QA_PROJECT) {
                                def app = openshift.newApp("weather:${QA_TAG}", "--name=weather")
                                app.narrow("svc").expose();

                                def dc = openshift.selector("dc", "weather")
                                while (dc.object().spec.replicas != dc.object().status.availableReplicas) {
                                    sleep 10
                                }
                                openshift.set("triggers", "dc/weather", "--manual")
                              }
                            }
                          }
                        }
                      }
                      stage('Deploy QA') {
                        steps {
                          script {
                            openshift.withCluster() {
                              openshift.withProject(env.QA_PROJECT) {
                                openshift.selector("dc", "weather").rollout().latest();
                              }
                            }
                          }
                        }
                      }
                stage('Promote to PROD?') {
              steps {
                timeout(time:15, unit:'MINUTES') {
                    input message: "Promote to PROD?", ok: "Promote"
                }
              }
            }
           stage('Tag for Prod') {
               steps {
                   script {
                     openshift.withCluster() {
                      openshift.tag("${env.QA_PROJECT}/weather:${QA_TAG}", "${env.QA_PROJECT}/weather:${PRODA_TAG}")
                       openshift.tag("${env.QA_PROJECT}/weather:${QA_TAG}", "${env.QA_PROJECT}/weather:${PRODB_TAG}")
                            }
                          }
                        }
                      }
             stage('Copy Image to PROD A') {
              steps {
                  script {
                      openshift.withCluster() {
                          openshift.withProject("${QA_PROJECT}") {
                              withCredentials([string(credentialsId: 'QA_CREDS', variable: 'QA_CREDS'),
                                               string(credentialsId: 'PRODA_CREDS', variable: 'PRODA_CREDS')]) {
                                  // call like this so we dont print credentials to logs
                                  sh '''
                                        set -x
                                        skopeo --debug copy --src-tls-verify=false --dest-tls-verify=false --src-creds="${QA_CREDS}" --dest-creds="${PRODA_CREDS}" "${QA_REGISTRY}/${QA_PROJECT}/weather:${PRODA_TAG}" "${PRODA_REGISTRY}/${PRODA_PROJECT}/weather:${PRODA_TAG}"
                                      '''
                              }
                          }
                      }
                  }
              }
            }
           stage('Deploy Image in Prod A') {
                        steps {
                          script {
                            openshift.withCluster(env.PRODA_CLUSTER) {
                              openshift.withProject(env.PRODA_PROJECT) {
                                openshift.selector("dc", "weather").rollout().latest();
                                slackSend (color: '#0eaf2b', message: "Success: Job - App is deployed in Prod A - check the weather here: http://weather.apps.<your-openshift-console>")
                              }
                            }
                      }
                      }
          }
             stage('Copy Image to PROD B') {
              steps {
                  script {
                      openshift.withCluster() {
                          openshift.withProject("${QA_PROJECT}") {
                              withCredentials([string(credentialsId: 'QA_CREDS', variable: 'QA_CREDS'),
                                               string(credentialsId: 'PRODB_CREDS', variable: 'PRODB_CREDS')]) {
                                  // call like this so we dont print credentials to logs
                                  sh '''
                                        set -x
                                        skopeo --debug copy --src-tls-verify=false --dest-tls-verify=false --src-creds="${QA_CREDS}" --dest-creds="${PRODB_CREDS}" "${QA_REGISTRY}/${QA_PROJECT}/weather:${PRODB_TAG}" "${PRODB_REGISTRY}/${PRODB_PROJECT}/weather:${PRODB_TAG}"
                                      '''
                              }
                          }
                      }
                  }
              }
            }
           stage('Deploy Image in Prod B') {
                        steps {
                          script {
                            openshift.withCluster(env.PRODB_CLUSTER) {
                              openshift.withProject(env.PRODB_PROJECT) {
                                openshift.selector("dc", "weather").rollout().latest();
                                slackSend (color: '#0eaf2b', message: "Success: Job - App is deployed in Prod B - check the weather here: http://weather.apps.<your-openshift-console>")
                              }
                            }                            
                      }
                      }
          }
          }
        }
  output:
  resources:
  postCommit:
