apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  selector:
    matchLabels:
      app: weather
  replicas: 1 
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: docker.io/daniyalj/weather:latest
        ports:
        - containerPort: 8080
