version: '3'
services:
  standalone:
    image: "grubykarol/locust:0.9.0-python3.6-alpine3.9"
    container_name: locust
    hostname: locust
    ports:
     - "8089:8089"
    environment:
      ATTACKED_HOST: http://localhost:8089
      LOCUST_MODE: standalone
      NO_PROXY: standalone
      TASK_DELAY: 1000
      QUIET_MODE: "${QUIET_MODE:-false}"
      LOCUST_OPTS: "--web-port 8089"
    volumes:
      - ./:/locust
